### ISSUE TITLE
Route for basic User management

### ISSUE THREAD

**Issue by kappuccino** [peerpx/peerpx#9]
This is a proposition about some router need to handle a user

**/login**
send `login` and `password`
return 200 if everything is correct and a JSON object in the body
return 500 (?) if the login fails ? (not sure about that one)

**/create**
Create a user, like a registration (new member that enroll himself)
send `login` and `password`
return 200 and a complete user in JSON (like the userid + I-do-not-know-yet)
return an error if something happened

**/update**
When a user update himself or an admin edit/save a user
send a `user struct`
return ? something like the updatePhoto ?

We need to talk about the cookie/token used to identify the user for a request...

**Comment by toorop** [comment]
Create: POST /user/  
Update: PUT /user
Login: POST /user/login
?

**Comment by kappuccino** [comment]
POST /login for short ?
